version: 'latest'
services:
  front-end:
    build: ./front-end
    ports:
     - "80:3000"
    volumes:
     - ./front-end:/app

  api-server:
    build: ./api-server
    ports:
     - "8080:8080"

  twitter-crawler:
    build: ./twitter-crawler
    volumes:
     - ./twitter-crawler:/app


