version: '3'
services:
  front-end:
    build: ./front-end
    ports:
     - "80:3000"

  api-server:
    build:
      context: ./api-server
      args:
        - JAR_FILE=./target/twittermining-0.0.1-SNAPSHOT.jar
    ports:
     - "8080:8080"

  twitter-crawler:
    build: ./twitter-crawler
    volumes:
     - ./twitter-crawler:/app

